import React from 'react';
import Paragraph from "@/components/commons/ui/paragraph";

const AnnouncementEs = () => {
    return (
        <>
            <h3 className={'text-center font-bold text-lg'}>Holiday Inn Club Vacations Adquiere Cuatro Resorts en México de Royal Resorts, Marcando la Primera Expansión Internacional para la Compañía</h3>
            <Paragraph>ORLANDO, FLA. – (23 de mayo de 2023) <a  className={"text-[#5897fb]"} href="https://hicv.com/" target="_blank">Holiday Inn Club Vacations Incorporated</a>, una compañía líder en la propiedad vacacional y socia de <a  className={"text-[#5897fb]"} href="https://www.ihgplc.com/en/" target="_blank">IHG® Hotels & Resorts</a> (IHG), anunció hoy que adquirió cuatro resorts frente a la playa en Cancún, Playa del Carmen y la Riviera Maya, México, de <a  className={"text-[#5897fb]"} href="https://www.royalresorts.com/" target="_blank">Royal Resorts®</a>, un pionero en la industria turística en el Caribe mexicano. La adquisición abarca la mayoría de las empresas de Royal Resorts, así como sus operaciones corporativas. Estos resorts serán las primeras propiedades de Holiday Inn Club Vacations Incorporated fuera de los Estados Unidos, ampliando aún más la cobertura de resorts de Holiday Inn Club Vacations e IHG, brindando a los huéspedes más opciones en destinos vacacionales.</Paragraph>

            <Paragraph>Los cuatros reconocidos resorts para familias adquiridos por Holiday Inn Club Vacations Incorporated – The Royal Sands®, The Royal Cancun®, The Royal Haciendas® y Grand Residences by Royal Resorts® – agregarán más de 850 villas a la creciente familia de resorts de destino de la compañía. La compañía estima que tomará aproximadamente un año para integrar totalmente estos resorts, y durante el proceso, los resorts seguirán operando normalmente.</Paragraph>

            <Paragraph>Una vez terminado, los clientes de IHG Hotels & Resorts podrán reservar en estas propiedades a través de IHG y disfrutar de los beneficios del programa de lealtad de IHG – <a  className={"text-[#5897fb]"} href="https://www.ihg.com/onerewards/content/us/en/home" target="_blank">IHG One Rewards</a> – incluyendo la capacidad de obtener y canjear puntos para estancias en hoteles. Estas propiedades se agregarán a la red mundial de IHG de 18 marcas y más de 6,000 hoteles en todo el mundo, añadiendo impresionantes destinos familiares a la creciente variedad de marcas IHG.</Paragraph>

            <Paragraph><b>John Staten, Presidente y Director General de Holiday Inn Club Vacations Incorporated</b>, señaló: “Estamos muy emocionados con estas noticias y lo que significan para Holiday Inn Club Vacations, y más aún para las familias que viajan con nosotros. Esta adquisición está alineada con nuestro plan de crecimiento, donde el crecer la preferencia de los huéspedes, así como crecer nuestra familia de resorts son dos pilares fundamentales interconectados que soportan nuestra misión de ser la marca favorita para viajes familiares. Con cuatro increíbles resorts ubicados en uno de los destinos de viajes para familias de más rápido crecimiento en el mundo – el pintoresco Caribe mexicano – la adquisición brinda una experiencia totalmente nueva y con todo incluido a nuestros dueños, socios del Club y huéspedes.”</Paragraph>

            <Paragraph><b>Keith Barr, Director Ejecutivo de IHG Hotels & Resorts</b>, dice: “Los huéspedes alrededor del mundo ahora contarán con más opciones para agregar a sus planes de viaje mientras también disfrutan de los fabulosos beneficios de nuestro programa IHG One Rewards para sus estancias actuales o futuras. La adición de estos galardonados resorts también demuestra la fortaleza de la familia de marcas de Holiday Inn y, ciertamente, la visión inquebrantable del fundador Kemmons Wilson, para crear una mejor forma de vacacionar, perdura hasta hoy.”</Paragraph>

            <Paragraph><b>Spence Wilson, Presidente del Consejo, Holiday Inn Club Vacations Incorporated</b>, comentó: “Desde que mi padre inició Holiday Inn Club Vacations hace más de 40 años, han habido muchos indicadores de crecimiento a lo largo del camino. Pocos pueden superar al anuncio de hoy – nuestra primera expansión fuera de los Estados Unidos. Estoy increíblemente orgulloso de nuestro equipo y veo hacia un futuro más brillante y aún más emocionante al dar la bienvenida en nuestra familia al equipo de Royal Resorts y sus dueños, miembros y huéspedes.”</Paragraph>

            <Paragraph><b>Dr. Kemil Rizk, Director General y Presidente de Royal Resorts</b>, agregó: “Creemos que esta operación encaja perfectamente y no podíamos pedir un mejor socio para continuar con nuestro legado desde que recibimos a nuestros primeros huéspedes en 1978. Al igual que nosotros, Holiday Inn Club Vacations es una empresa pionera con una colección de resorts para familias y una reputación de servicio y calidad sobresalientes. Holiday Inn Club Vacations se dedica a brindar experiencias vacacionales inolvidables para las familias – algo que se alinea perfectamente con la misión y los valores de Royal Resorts, nuestras membresías de propiedad vacacional basadas en puntos o semanas fijas y el compromiso diario de nuestro equipo por la calidad en el servicio.”</Paragraph>

            <Paragraph>La transacción fue revisada y aprobada por la Comisión Federal de Competencia Económica, (COFECE) del gobierno de México. Como parte de un acuerdo independiente, Tortuga Resorts UK Limited adquirió las entidades que son dueñas y operan el resto de las propiedades de Royal Resorts - The Royal Islander® y Royal Uno® All Inclusive Resort & Spa.</Paragraph>

            <Paragraph><b>Acerca de los galardonados resorts que Holiday Inn Club Vacations Incorporated adquirió de Royal Resorts</b></Paragraph>

            <Paragraph><i>The Royal Sands</i></Paragraph>
            <Paragraph>Localizado en Cancún, el resort de 6.9 hectáreas cuenta con 340 villas de dos recámaras, tres albercas y una alberca infantil, cuatro restaurantes, tres bares, un gimnasio, spa, kids club supervisado, centro de actividades, una marina junto a la laguna para veleros y kayaks, una tienda, cafetería y una agencia de viajes, además del acceso a la playa.</Paragraph>

            <Paragraph><i>The Royal Cancun</i></Paragraph>
            <Paragraph>Ubicado en la costa norte de Cancún con vista a la bahía e Isla Mujeres, el resort de 3 hectáreas cuenta con 201 villas de dos recámaras y dos albercas, dos restaurantes de servicio completo y dos bares. También tiene un gimnasio, canchas de tenis, centro de actividades y kids club supervisado, así como una agencia de viajes, tienda de conveniencia y tienda de regalos. El resort tiene acceso a una playa que es perfecta para los niños. Otras actividades populares en el resort son el esnórquel, paseos en velero y kayaks.</Paragraph>

            <Paragraph><i>The Royal Haciendas</i></Paragraph>
            <Paragraph>Localizado en la Riviera Maya, cinco minutos al norte de Playa el Carmen, el resort de 9.4 hectáreas cuenta con 252 villas de dos recámaras con tinas de hidromasaje en los balcones privados y tiene cuatro albercas, cuatro restaurantes de servicio completo y cinco bares. También cuenta con un spa, gimnasio, salón de belleza y centro de buceo, agencia de viajes, centro de actividades, kids club supervisado, alberca infantil con área de juegos acuáticos, cuatro grandes tinas de hidromasaje en el asoleadero, canchas de tenis y una tienda de conveniencia. El resort está ubicado a la orilla de una bahía en la comunidad CoraSol y está a pocos metros de un campo de golf.</Paragraph>

            <Paragraph><i>Grand Residences by Royal Resorts</i></Paragraph>
            <Paragraph>También localizado al sur de Cancún, en el tranquilo pueblo costero de Puerto Morelos, Grand Residences by Royal Resorts ofrece lujo en la playa. El resort de 5.3 hectáreas cuenta con 62 villas de dos, tres y cuatro recámaras. Las amplias unidades elegantemente amuebladas tienen muebles de madera tropical, aparatos electrodomésticos y amenidades de gama alta, terrazas privadas, baños spa y jacuzzis. Algunas unidades más grandes cuentan con albercas de inmersión privadas y jardines. El resort tiene cuatro albercas, dos restaurantes, un bar y grill en la playa, bar de alberca, lobby bar y café, gimnasio, spa, actividades diarias, kids club supervisado, canchas de tenis y una tienda de alimentos gourmet.</Paragraph>

            <Paragraph>Un breve resumen en video de los resorts que Holiday Inn Club Vacations adquirió puede verse aquí.</Paragraph>
            <br/>
                <iframe
                    className={"m-auto"}
                    width="560" height="315" src="https://www.youtube.com/embed/zkhGW_ISFu8" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                <br/>
                    <br/>

                        <Paragraph><b>Acerca de Holiday Inn Club Vacations Incorporated</b></Paragraph>
                        <Paragraph>Con desarrollos en los Estados Unidos y el Caribe mexicano, Holiday Inn Club Vacations Incorporated es una empresa de resorts, bienes raíces y viajes con una misión de ser la marca favorita de viajes para familias, al brindar experiencias vacacionales inolvidables fáciles de planificar que fortalecen a las familias.</Paragraph>

                        <Paragraph>La compañía, con base en Orlando, Florida, ha sido un líder en la industria de propiedad vacacional desde 1982, cuando el fundador de Holiday Inn®, Kemmons Wilson, inauguró la propiedad insignia de la compañía, Holiday Inn Club Vacations® at Orange Lake Resort, junto al Orlando’s Walt Disney World® Resort.</Paragraph>

                        <Paragraph>Hoy, el portafolio de resorts de Holiday Inn Club Vacations se extiende por todos los Estados Unidos y hacía el Caribe mexicano, con la expansión internacional de la compañía en mayo de 2023. A lo largo de su historia, la compañía ha mantenido los valores familiares centrales, fieles a su familia fundadora Wilson, mientras que persigue agresivamente el crecimiento, transformando su modelo de participación de sus miembros y construyendo un equipo líder en la industria, apasionado por la experiencia del huésped.</Paragraph>

                        <Paragraph><b>Acerca de Royal Resorts</b></Paragraph>
                        <Paragraph>Fundado en Cancún en 1975, Royal Resorts® es una compañía pionera del turismo en el Caribe mexicano y en la industria de propiedad vacacional internacional. Ha recibido visitantes desde 1978 a sus resorts en Cancún y la Riviera Maya donde las familias disfrutan una combinación perfecta de belleza de playa, servicios excepcionales para los huéspedes y una hospitalidad distintiva. Las amplias villas están equipadas con todo lo que necesitan para su estancia, y disfrutan de una variedad de amenidades para unas vacaciones inolvidables, incluyendo actividades diarias para todas las edades, Kids clubs, deportes acuáticos no motorizados, albercas, gimnasios y spas, además de una variada escena gastronómica.</Paragraph>

                        <Paragraph>Cada resort tiene su propio carácter y encanto, y todos tienen un ambiente familiar y un espíritu de comunidad, con amistades forjadas entre los socios y los anfitriones a lo largo de los años. Los resorts de la Riviera Maya– The Royal Haciendas y Grand Residences – contienen diseños y elementos arquitectónicos inspirados en las grandes haciendas antiguas de México. Para más información, visite <a  className={"text-[#5897fb]"} href="https://www.royalresorts.com/" target="_blank">www.royalresorts.com</a>.</Paragraph>

                        <Paragraph><b>Acerca de IHG Hotels & Resorts</b></Paragraph>
                        <Paragraph><a  className={"text-[#5897fb]"} href="https://www.ihgplc.com/en/" target="_blank">IHG Hotels & Resorts</a> [LON:IHG, NYSE:IHG (ADRs)] es una empresa hotelera mundial, con el objetivo de brindar una Verdadera Hospitalidad por Siempre.</Paragraph>

                        <Paragraph>Con una familia de 18 marcas de hotel y <a  className={"text-[#5897fb]"} href="https://www.ihg.com/onerewards/content/us/en/home" target="_blank">IHG One Rewards</a>, uno de los programas de lealtad hotelera más grande del mundo, IHG cuenta con más de 6,000 hoteles en más de 100 países, y más de 1,800 en proceso de desarrollo.</Paragraph>

                        <ul className={"list-disc pl-5"}>
                            <li><b>Lujo y Estilo de Vida: </b> <a  className={"text-[#5897fb]"} href="https://www.sixsenses.com/en" target="_blank">Six Senses Hotels Resorts Spas</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/regent/hotels/us/en/reservation" target="_blank">Regent Hotels & Resorts</a>, <a  className={"text-[#5897fb]"} href="https://www.intercontinental.com/hotels/gb/en/reservation" target="_blank">InterContinental Hotels & Resorts</a>, <a  className={"text-[#5897fb]"} href="https://www.vignettecollectionhotels.com/hotels/us/en/reservation" target="_blank">Vignette Collection</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/kimptonhotels/hotels/us/en/reservation" target="_blank">Kimpton Hotels & Restaurants, Hotel Indigo</a></li>
                            <li><b>Premium: </b> <a  className={"text-[#5897fb]"} href="https://www.ihg.com/voco/hotels/gb/en/reservation" target="_blank">voco hotels</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/hualuxe/hotels/gb/en/reservation" target="_blank">HUALUXE Hotels & Resorts</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/crowneplaza/hotels/gb/en/reservation" target="_blank">Crowne Plaza Hotels & Resorts</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/evenhotels/hotels/us/en/reservation" target="_blank">EVEN Hotels</a></li>
                            <li><b>Esenciales: </b> <a  className={"text-[#5897fb]"} href="https://www.ihg.com/holidayinn/hotels/gb/en/reservation" target="_blank">Holiday Inn Hotels & Resorts</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/holidayinnexpress/hotels/gb/en/reservation" target="_blank">Holiday Inn Express</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/avidhotels/hotels/us/en/reservation" target="_blank">avid hotels</a></li>
                            <li><b>Suites: </b> <a  className={"text-[#5897fb]"} href="https://www.atwellsuites.com/hotels/gb/en/reservation" target="_blank">Atwell Suites</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/staybridge/hotels/gb/en/reservation" target="_blank">Staybridge Suites</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/holidayinnclubvacations/hotels/us/en/reservation" target="_blank">Holiday Inn Club Vacations</a>, <a  className={"text-[#5897fb]"} href="https://www.ihg.com/candlewood/hotels/us/en/reservation" target="_blank">Candlewood Suites</a></li>
                            <li><b>Socios Exclusivos: </b> <a  className={"text-[#5897fb]"} href="https://www.ihg.com/content/us/en/iberostar-beachfront-resorts" target="_blank">Iberostar Beachfront Resorts</a></li>
                        </ul>

                        <Paragraph>InterContinental Hotels Group PLC es la compañía titular de la propiedad del Grupo y está constituida y registrada en Inglaterra y Gales. Aproximadamente 325,000 personas trabajan en los hoteles y en las oficinas corporativas de IHG en todo el mundo.</Paragraph>

                        <Paragraph>Visítenos en línea para conocer más acerca de nuestros <a  className={"text-[#5897fb]"} href="https://www.ihg.com/hotels/gb/en/reservation" target="_blank">hoteles y reservaciones</a> y de <a  className={"text-[#5897fb]"} href="https://www.ihg.com/onerewards/content/us/en/home" target="_blank">IHG One Rewards</a>. Para descargar la nueva app IHG One Rewards, visite las tiendas <a  className={"text-[#5897fb]"} href="https://apps.apple.com/us/app/ihg-hotel-deals-rewards/id368217298" target="_blank">Apple App</a> o <a  className={"text-[#5897fb]"} href="https://play.google.com/store/apps/details?id=com.ihg.apps.android&pli=1" target="_blank">Google Play</a>.</Paragraph>

                        <Paragraph>Para conocer nuestras últimas noticias, <a  className={"text-[#5897fb]"} href="https://www.ihgplc.com/en/news-and-media" target="_blank">visite nuestra Sala de Prensa</a> o síganos en <a  className={"text-[#5897fb]"} href="https://www.linkedin.com/authwall?trk=bf&trkInfo=AQHzeXeNsw3BeAAAAYhJpVzQ7hrfRQSMlpz685eDbXDn1LWPTrqMcrPTVXnzMQ-Hmu2JA0eKdmS-W9YpsoIzx-RKg2umbrpa1fsThHBF3PekuvTtAMEA7-NKaGQJq_X_Nfa5M5A=&original_referer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fihghotels%26resorts%2F" target="_blank">LinkedIn   </a>, <a  className={"text-[#5897fb]"} href="https://www.facebook.com/IHGCorporate/" target="_blank">Facebook</a> y <a  className={"text-[#5897fb]"} href="https://twitter.com/IHGCorporate" target="_blank">Twitter</a>.</Paragraph>

                        <Paragraph>Contacto de Medios:<br/>
                            Ashley Pipa, Holiday Inn Club Vacations<br/>
                            apipa@holidayinnclub.com<br/>
                            407.315.8866
                        </Paragraph>
        </>
    );
};

export default AnnouncementEs;